### ISSUE TITLE
Ephemeral dashboard crashes on Chrome macOS

### ISSUE THREAD

**Issue by Nexucis** [perses/perses#2063]
### What did you do?

1. I have duplicated a dashboard to create en ephemeral dashboard with a TTL `1d`
2. Then on the project view I clicked on the tab `Ephemeral Dashboard`

### What did you expect to see?

To see the list of the Ephemeral Dashboard

### What did you see instead? Under which circumstances?

The page crashed: 

<img width="716" alt="image" src="https://github.com/perses/perses/assets/4548045/8558a15f-cd0a-45c8-9daa-9d4a093d8da0">

stack trace in the browser console
```
RangeError: Value need to be finite number for Intl.RelativeTimeFormat.prototype.format()
    at RelativeTimeFormat.format (<anonymous>)
    at k (main.js:349:5838)
    at Object.renderCell (949.js:1:9242)
    at main.js:246:44490
    at Ql (main.js:368:20406)
    at xn (main.js:370:1587)
    at Hc (main.js:370:46855)
    at Nc (main.js:370:40517)
    at td (main.js:370:40445)
    at Xu (main.js:370:40298)
```

Note that the issue only appear when using Chrome on MacOS (only tested with m2).
Tested with firefox on windows + MacOS it works. And it works with Google Chrome on Windows

### System information

Darwin 23.5.0 arm64

### Perses version

v0.46.0-rc1, v0.46.0, main branch

**Comment by Nexucis** [comment]
with the last version I am not able to reproduce this issue.

**Comment by Nexucis** [comment]
reopening this, I have made more manual tests and actually the bug is still there

**Comment by Nexucis** [comment]
closed thanks to https://github.com/perses/perses/pull/2778
